using UnityEngine;

public class PlayerInteractable : MonoBehaviour
{
    public Camera cam;
    public float distance = 3f;
    public LayerMask mask;
    private PlayerUI playerUI;

    void Start()
    {
       playerUI = GetComponent<PlayerUI>();
    }

    void Update()
    {
        playerUI.UpdateText(string.Empty);
        Ray ray = new Ray(cam.transform.position, cam.transform.forward);
        RaycastHit hitInfo;
        if (Physics.Raycast(ray, out hitInfo, distance, mask))
        {
            if (hitInfo.collider.GetComponent<Interactable>() != null)
            {
                Interactable interactable = hitInfo.collider.GetComponent<Interactable>();
                playerUI.UpdateText(interactable.promptMessage);
                if (Input.GetButtonDown("Interact"))
                {
                    Debug.Log("Player pressed E");
                    interactable.BaseInteract();
                }
            }
        }

    }
}
